import { FormEvent, useEffect, useState } from 'react';
import { importFacilitySource, listFacilities } from '../api/vda';

export default function Facilities() {
  const [token, setToken] = useState(sessionStorage.vdaToken || import.meta.env.VITE_DEV_AUTH_TOKEN || '');
  const [filters, setFilters] = useState({ state: '', district: '', hospitalType: '', pmjay: '', query: '' });
  const [facilities, setFacilities] = useState<any[]>([]); const [error, setError] = useState(''); const [message, setMessage] = useState('');
  const load = () => listFacilities(token, filters).then(setFacilities).catch((e) => setError(e.message));
  useEffect(() => { if (token) load(); }, []);
  const search = (event: FormEvent) => { event.preventDefault(); setError(''); load(); };
  const upload = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = new FormData(event.currentTarget); const documentId = String(form.get('documentId') || ''); const state = String(form.get('state') || ''); const file = form.get('file'); if (!(file instanceof File) || !documentId || !state) { setError('Source document ID, source state, and file are required.'); return; } try { const result = await importFacilitySource(token, documentId, state, file); setMessage(`${result.imported} source-backed facilities imported.`); setError(''); load(); } catch (e: any) { setError(e.message); } };
  return <><h1>Facilities</h1><section className="panel"><b>Structured, source-backed facilities</b><p>Unknown fields remain unknown. “Nearest” is not shown without coordinates.</p><input placeholder="Admin bearer token" value={token} onChange={e => setToken(e.target.value)} /></section><section className="panel"><h2>Search facilities</h2><form onSubmit={search}><input placeholder="State" value={filters.state} onChange={e => setFilters({ ...filters, state: e.target.value })} /><input placeholder="District" value={filters.district} onChange={e => setFilters({ ...filters, district: e.target.value })} /><input placeholder="Facility type" value={filters.hospitalType} onChange={e => setFilters({ ...filters, hospitalType: e.target.value })} /><input placeholder="Hospital name" value={filters.query} onChange={e => setFilters({ ...filters, query: e.target.value })} /><select value={filters.pmjay} onChange={e => setFilters({ ...filters, pmjay: e.target.value })}><option value="">All facilities</option><option value="true">PM-JAY listed</option><option value="false">Not PM-JAY listed</option></select><button>Search</button></form><p>{error}</p></section><section className="panel"><h2>Import authoritative source</h2><form onSubmit={upload}><input name="documentId" placeholder="Active knowledge document ID" required /><input name="state" placeholder="Source state" required /><input name="file" type="file" accept=".pdf,.csv,.json" required /><button>Validate and import</button></form><p>{message}</p></section><section className="panel"><h2>Results ({facilities.length})</h2>{facilities.map(f => <article key={f.id}><b>🏥 {f.name}</b><p>{[f.district, f.state].filter(Boolean).join(', ')}</p><p>PM-JAY: {f.pmjayStatus === true ? 'Available' : f.pmjayStatus === false ? 'Not listed' : 'Unknown'} · {f.hospitalType || 'Type unknown'}</p>{f.contactNumber && <p>Contact: {f.contactNumber}</p>}<small>Source document: {f.sourceDocumentId}</small></article>)}</section></>;
}
