import { useEffect, useState } from 'react';
import { confirmPatientMedication, listPatientAdherence, listPatientMedications, listSyntheticPatients } from '../api/vda';

export default function Medications() {
  const [token, setToken] = useState(sessionStorage.vdaToken || ''); const [patients, setPatients] = useState<any[]>([]); const [patientId, setPatientId] = useState(''); const [medications, setMedications] = useState<any[]>([]); const [events, setEvents] = useState<any[]>([]); const [error, setError] = useState('');
  const loadPatients = () => listSyntheticPatients(token).then((items) => { setPatients(items); if (!patientId && items[0]) setPatientId(items[0].id); }).catch((e) => setError(e.message));
  const load = () => { if (!patientId) return; Promise.all([listPatientMedications(token, patientId), listPatientAdherence(token, patientId)]).then(([meds, adherence]) => { setMedications(meds); setEvents(adherence); }).catch((e) => setError(e.message)); };
  useEffect(() => { if (token) loadPatients(); }, []);
  return <><h1>Medications & adherence</h1><section className="panel"><b>Development-only synthetic patient data — not real patient data.</b><input placeholder="Admin bearer token" value={token} onChange={e => setToken(e.target.value)} /><button onClick={loadPatients}>Load patients</button><select value={patientId} onChange={e => setPatientId(e.target.value)}><option value="">Select patient</option>{patients.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select><button onClick={load}>Load medication records</button><p>{error}</p></section><section className="panel"><h2>Medication list</h2><table><thead><tr><th>Medicine</th><th>Strength</th><th>Frequency</th><th>Verification</th><th>State</th><th>Source prescription</th><th>Action</th></tr></thead><tbody>{medications.map(m => <tr key={m.id}><td>{m.name}</td><td>{m.strength || 'Unknown'}</td><td>{m.frequency || 'Unknown'}</td><td>{m.verificationStatus}</td><td>{m.status}</td><td>{m.sourcePrescriptionId}</td><td>{m.verificationStatus==='VALIDATION_REQUIRED'?<button onClick={()=>confirmPatientMedication(token,patientId,m.id).then(load).catch(e=>setError(e.message))}>Confirm medication</button>:'Confirmed'}</td></tr>)}</tbody></table><p>Prescription approval and medication confirmation are separate review actions.</p></section><section className="panel"><h2>Adherence events</h2><table><thead><tr><th>Medication</th><th>Date</th><th>Schedule</th><th>Status</th><th>Confirmed</th><th>Source</th></tr></thead><tbody>{events.map(event => <tr key={event.id}><td>{medications.find(m => m.id === event.medicationId)?.name || event.medicationId}</td><td>{event.scheduledDate}</td><td>{event.scheduleSlot || 'Unknown'}</td><td>{event.status}</td><td>{new Date(event.confirmedAt).toLocaleString()}</td><td>{event.source}</td></tr>)}</tbody></table></section></>;
}
