import { api, base } from './client'; import type {Document,Turn} from '../types/api';
export const sendTurn=(id:string,token:string|undefined,input_text:string,language:string)=>api<Turn>(`/sessions/${id}/turns`,token,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({input_text,speaker:'self',language})});
export const closeSession=(id:string,token?:string)=>api<void>(`/sessions/${id}/close`,token,{method:'POST'});
export const listDocs=(token?:string)=>api<Document[]>('/admin/knowledge/documents',token);
export const searchKnowledge=(token:string|undefined,q:string)=>api<any>(`/admin/knowledge/search?query=${encodeURIComponent(q)}`,token);
export const lifecycle=(token:string|undefined,id:string,action:string)=>api(`/admin/knowledge/documents/${id}/${action}`,token,{method:'POST'});
export const getKnowledgeDocument=(token:string|undefined,id:string)=>api<any>(`/admin/knowledge/documents/${id}`,token);
export const uploadKnowledgeDocument=(token:string|undefined,fields:Record<string,string>,file:File)=>{const body=new FormData();Object.entries(fields).forEach(([key,value])=>body.append(key,value));body.append('file',file);return api<any>('/admin/knowledge/documents',token,{method:'POST',body});};
export const health=(token:string|undefined,path:string)=>api<any>(`/health/${path}`,token);
export const listSyntheticPatients=(token?:string)=>api<any[]>('/dev/demo/patients',token);
export const listLocalPrototypePatients=(token?:string)=>api<any[]>('/dev/demo/patient-selection',token);
export const startLocalPrototypeSession=(token:string|undefined,id:string)=>api<any>(`/dev/demo/patient-selection/${encodeURIComponent(id)}/session`,token,{method:'POST'});
export const createSyntheticPatient=(token:string|undefined,body:any)=>api<any>('/dev/demo/patients',token,{method:'POST',body:JSON.stringify(body)});
export const updateSyntheticPatient=(token:string|undefined,id:string,body:any)=>api<any>(`/dev/demo/patients/${id}`,token,{method:'PATCH',body:JSON.stringify(body)});
export const deleteSyntheticPatient=(token:string|undefined,id:string)=>api(`/dev/demo/patients/${id}`,token,{method:'DELETE'});
export const startSyntheticSession=(token:string|undefined,id:string)=>api<any>(`/dev/demo/patients/${id}/session`,token,{method:'POST'});
export const getSessionPatientContext=(token:string|undefined,sessionId:string)=>api<any>(`/dev/demo/sessions/${sessionId}/patient-context`,token);
export const getClinicalReviewState=(token:string|undefined,sessionId:string)=>api<{reviewRequested:boolean;teleconsultationOffered:boolean;teleconsultationConfigured:boolean;messages:Array<{speaker:'PATIENT'|'CLINICIAN';text:string;createdAt:string}>}>(`/sessions/${sessionId}/clinical-review`,token);
export const requestClinicalReviewTeleconsultation=(token:string|undefined,sessionId:string)=>api<{teleconsultationConfigured:boolean}>(`/sessions/${sessionId}/clinical-review/teleconsultation`,token,{method:'POST'});
export const recordFeedback=(token:string|undefined,body:any)=>api('/dev/demo/feedback',token,{method:'POST',body:JSON.stringify(body)});
export const listFacilities=(token:string|undefined,filters:Record<string,string>)=>api<any[]>(`/admin/facilities?${new URLSearchParams(Object.entries(filters).filter(([, value]) => value !== ''))}`,token);
export const importFacilitySource=(token:string|undefined,documentId:string,state:string,file:File)=>{const body=new FormData();body.append('state',state);body.append('file',file);return api<any>(`/admin/facilities/import/documents/${documentId}/file`,token,{method:'POST',body});};
export const listSchemes=(token:string|undefined,filters:Record<string,string>)=>api<any[]>(`/admin/schemes?${new URLSearchParams(Object.entries(filters).filter(([, value]) => value !== ''))}`,token);
export const listPatientMedications=(token:string|undefined,patientId:string)=>api<any[]>(`/dev/demo/patients/${patientId}/medications`,token);
export const confirmPatientMedication=(token:string|undefined,patientId:string,medicationId:string)=>api<any>(`/dev/demo/patients/${patientId}/medications/${medicationId}/confirm`,token,{method:'POST'});
export const listPatientAdherence=(token:string|undefined,patientId:string)=>api<any[]>(`/dev/demo/patients/${patientId}/medications/adherence/events`,token);
export const schemeEligibility=(token:string|undefined,schemeId:string)=>api<any>(`/admin/schemes/${encodeURIComponent(schemeId)}/eligibility`,token);
export const ragQuality=(token?:string)=>api<any>('/admin/evaluation/rag-quality',token);
export const runControlledEvaluation=(token?:string)=>api<any>('/admin/evaluation/rag-quality/run-controlled',token,{method:'POST'});
export const dashboardSummary=(token?:string)=>api<any>('/admin/evaluation/dashboard-summary',token);
export const listClinicalEscalations=(token:string|undefined, filters:Record<string,string>={})=>api<any[]>(`/admin/escalations?${new URLSearchParams(Object.entries(filters).filter(([, value]) => value !== ''))}`,token);
export const getClinicalEscalation=(token:string|undefined,id:string)=>api<any>(`/admin/escalations/${id}`,token);
export const getOpenClinicalEscalationCount=(token?:string)=>api<{open:number}>('/admin/escalations/open-count',token);
export const reviewClinicalEscalation=(token:string|undefined,id:string,body:{outcome:'TRUE_POSITIVE'|'FALSE_POSITIVE'|'ANNOTATED';note?:string})=>api<any>(`/admin/escalations/${id}/review`,token,{method:'PATCH',body:JSON.stringify(body)});
export const reviewClinicalResponse=(token:string|undefined,id:string,body:{decision:'APPROVED'|'CORRECTED'|'ANNOTATED';note?:string;correctedResponse?:string})=>api<any>(`/admin/escalations/${id}/response-review`,token,{method:'PATCH',body:JSON.stringify(body)});
export const sendClinicianMessage=(token:string|undefined,id:string,message:string,idempotencyKey=crypto.randomUUID())=>api<any>(`/admin/escalations/${id}/messages`,token,{method:'POST',headers:{'Idempotency-Key':idempotencyKey},body:JSON.stringify({message})});
export const endClinicalChat=(token:string|undefined,id:string,idempotencyKey=crypto.randomUUID())=>api<any>(`/admin/escalations/${id}/end-clinical-chat`,token,{method:'POST',headers:{'Idempotency-Key':idempotencyKey}});
export const listPrescriptions=(token:string|undefined,patientId:string)=>api<any[]>(`/dev/demo/patients/${patientId}/prescriptions`,token);
export const approvePrescription=(token:string|undefined,patientId:string,id:string)=>api<any>(`/dev/demo/patients/${patientId}/prescriptions/${id}/approve`,token,{method:'POST'});
export const uploadPrescription=(token:string|undefined,patientId:string,file:File)=>{const body=new FormData();body.append('file',file);return api<any>(`/dev/demo/patients/${patientId}/prescriptions`,token,{method:'POST',body});};
export const uploadSessionPrescription=(token:string|undefined,sessionId:string,file:File)=>{const body=new FormData();body.append('file',file);return api<any>(`/sessions/${sessionId}/prescriptions`,token,{method:'POST',body});};
const voiceRequest = async (path: string, token: string | undefined, init: RequestInit) => {
  const headers = new Headers(init.headers);
  if (token) headers.set('Authorization', `Bearer ${token}`);
  headers.set('X-Correlation-Id', crypto.randomUUID());
  const response = await fetch(base + path, { ...init, headers });
  if (!response.ok) throw new Error('Voice service unavailable');
  return response;
};
export const transcribeVoice = async (audio: Blob, token: string | undefined, languageCode: string) => {
  const form = new FormData();
  form.append('audio', audio, 'vda-recording.webm');
  form.append('language_code', languageCode);
  return (await voiceRequest('/voice/stt', token, { method: 'POST', body: form })).json() as Promise<{ transcript: string }>;
};
export const synthesizeVoice = async (text: string, token: string | undefined, languageCode: string) =>
  (await voiceRequest('/voice/tts', token, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ text, language_code: languageCode }) })).blob();
